apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |
    # Your default mosquitto.conf configuration here
    persistence true
    persistence_location /mosquitto/data/
    log_dest file /mosquitto/log/mosquitto.log
    allow_anonymous true
    listener 1883
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto
        volumeMounts:
        - name: mosquitto-config-volume
          mountPath: /mosquitto/config
        - name: mosquitto-data-volume
          mountPath: /mosquitto/data
        - name: mosquitto-log-volume
          mountPath: /mosquitto/log
      volumes:
      - name: mosquitto-config-volume
        configMap:
          name: mosquitto-config
      - name: mosquitto-data-volume
        persistentVolumeClaim:
          claimName: mosquitto-pvc
      - name: mosquitto-log-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
spec:
  ports:
  - port: 1883
    targetPort: 1883
  selector:
    app: mosquitto
